pipeline:
  build:
    image: kkarczmarczyk/node-yarn
    commands:
      - yarn
      - yarn build
      - yarn test
    environment:
      - AWS_BUCKET=vivo-em-nos-staging
      - AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
    when:
      event: [push]

  publish:
    image: plugins/ecr
    access_key: ${PROD_AWS_ACCESS_KEY_ID}
    secret_key: ${PROD_AWS_SECRET_ACCESS_KEY}
    repo: ${VEN_ECR_REPO}.dkr.ecr.us-west-1.amazonaws.com/vivos-em-nos
    region: us-west-1
    build_args:
      - PUBLISH_S3=true
      - AWS_BUCKET=vivo-em-nos-production
      - AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
      - CLOUDFRONT_DISTRIBUTION_ID=${PROD_AWS_CLOUDFRONT_DISTRIBUTION_ID}
      - GRAPHQL_URL=https://data.vivosemnos.org/graphql
      - SERVER_DOMAIN=https://server.vivosemnos.org
    when:
      status: success
      branch: [master]

  deploy:
    image: peloton/drone-ecs

    region: us-west-1
    access_key: ${PROD_AWS_ACCESS_KEY_ID}
    secret_key: ${PROD_AWS_SECRET_ACCESS_KEY}
    family: server
    docker_image: ${VEN_ECR_REPO}.dkr.ecr.us-west-1.amazonaws.com/vivos-em-nos
    tag: latest
    service: vivos-em-nos
    # task_role_arn: arn:aws:iam::012345678901:role/rolename
    environment_variables:
      - NODE_ENV=production
      - NEW_RELIC_APP_NAME=vivos-em-nos-production
      - PORT=5005
      - AWS_ACCESS_KEY_ID=${VEN_AWS_ACCESS_KEY_ID}
      - AWS_BUCKET=${VEN_AWS_BUCKET}
      - AWS_SECRET_ACCESS_KEY=${VEN_AWS_SECRET_ACCESS_KEY}
      - CLOUDFRONT_DISTRIBUTION_ID=${VEN_CLOUDFRONT_DISTRIBUTION_ID}
      - DATABASE_URL=${VEN_DATABASE_URL}
      - GRAPHQL_URL=${VEN_GRAPHQL_URL}
      - NEW_RELIC_LICENSE_KEY=${VEN_NEW_RELIC_LICENSE_KEY}
      - SCHEMA_NAME=${VEN_SCHEMA_NAME}
      - SENTRY_DSN=${VEN_SENTRY_DSN}
      - NEW_RELIC_NO_CONFIG_FILE=true
      - SERVER_DOMAIN=${VEN_SERVER_DOMAIN}
    port_mappings:
      - 5005 5005
    memoryReservation: 128
    cpu: 512
    desired_count: 1
    deployment_configuration: 50 200
    when:
      status: success
      branch: [master]

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]

  # publish-client:
  #   s3:
  #     image: plugins/s3
  #     bucket: vivo-em-nos-production
  #     access_key:
  #     secret_key:
  #     source: dist/**/*
  #     target: /
