pipeline:
  build:
    image: kkarczmarczyk/node-yarn
    commands:
      - yarn
      - yarn test

  publish:
    image: plugins/docker
    repo: nossas/vivos-em-nos
    username: lpirola
    password: ${DOCKER_PASSWORD}
    tags:
      - ${DRONE_BRANCH}
    build_args:
      - AWS_BUCKET=vivos-em-nos
      - AWS_ACCESS_KEY_ID=${PROD_AWS_SECRET_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${PROD_AWS_ACCESS_KEY_ID}
      - CLOUDFRONT_DISTRIBUTION_ID=${PROD_AWS_CLOUDFRONT_DISTRIBUTION_ID}
      - NODE_ENV=production
      - NEW_RELIC_HOME=./src
      - PORT=5001
      - APP_DOMAIN=server.vivosemnos.org
    when:
      status: success
      branch: [master]

  # deploy:
  #   image: peloton/drone-ecs
  #   access_key:
  #   secret_key:
  #   service: vivos-em-nos
  #   region: us-west-1
  #   family: server
  #   image_name: nossas/vivos-em-nos
  #   image_tag: latest
  #   environment_variables:
  #     - DATABASE_URI=database uri
  #   port_mappings:
  #     - 5001 5001
  #   memory: 128
  #   when:
  #     status: success
  #     branch: [master]

  notify:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: n_tech
    username: CI - ${DRONE_REPO_NAME}
    when:
      event: [ push, tag, build, publish, deployment, pull_request ]
      status: [ success, failure ]
