FROM kkarczmarczyk/node-yarn
MAINTAINER Nossas <tech@nossas.org>

ARG AWS_BUCKET=vivo-em-nos-staging
ARG AWS_ACCESS_KEY_ID=xxx
ARG AWS_SECRET_ACCESS_KEY=yyy
ARG CLOUDFRONT_DISTRIBUTION_ID=zzz
ARG NODE_ENV=production
ARG PUBLISH_S3=false
ARG GRAPHQL_URL=http://localhost:3003/graphql
ARG SERVER_DOMAIN=http://localhost:5001
ENV NEW_RELIC_HOME=./src NODE_MODULES_CACHE=false NPM_CONFIG_PRODUCTION=false PORT=5001

RUN mkdir /code
WORKDIR /code

COPY package.json yarn.lock /code/
RUN yarn
COPY . /code

RUN AWS_BUCKET=$AWS_BUCKET \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    NODE_ENV=$NODE_ENV \
    CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID \
    PUBLISH_S3=$PUBLISH_S3 \
    GRAPHQL_URL=$GRAPHQL_URL \
    SERVER_DOMAIN=$SERVER_DOMAIN \
    yarn run build

CMD ["yarn", "start"]

EXPOSE 5001
