FROM kkarczmarczyk/node-yarn
MAINTAINER Nossas <tech@nossas.org>

ARG PUBLISH_S3=false
ARG NODE_ENV=production
ARG NEW_RELIC_APP_NAME=vivos-em-nos-staging
ARG PORT=5005
ARG AWS_ACCESS_KEY_ID=xxx
ARG AWS_BUCKET=vivo-em-nos-staging
ARG AWS_SECRET_ACCESS_KEY=yyy
ARG CLOUDFRONT_DISTRIBUTION_ID=zzz
ARG DATABASE_URL=postgres://postgres@localhost/vivo-em-nos-pwa
ARG GRAPHQL_URL=http://localhost:3003/graphql
ARG NEW_RELIC_LICENSE_KEY=xxx
ARG SCHEMA_NAME=public
ARG SENTRY_DSN=xxx
ARG NEW_RELIC_NO_CONFIG_FILE=true
ARG SERVER_DOMAIN=http://localhost:5001

ENV NEW_RELIC_HOME=./src PORT=5001

RUN mkdir /code
WORKDIR /code

COPY package.json yarn.lock /code/
RUN yarn
COPY . /code

RUN AWS_BUCKET=$AWS_BUCKET \
    AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
    AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
    NODE_ENV=$NODE_ENV \
    CLOUDFRONT_DISTRIBUTION_ID=$CLOUDFRONT_DISTRIBUTION_ID \
    PUBLISH_S3=$PUBLISH_S3 \
    GRAPHQL_URL=$GRAPHQL_URL \
    SERVER_DOMAIN=$SERVER_DOMAIN \
    yarn run build

CMD ["yarn", "start"]

EXPOSE 5001
