version: '2.1'

volumes:
  postgres-data:
    driver: local
  #redis-data:
  #  driver: local
  node-modules:
    driver: local

services:
  postgres:
    image: postgres:9.6.1
    ports:
      - 5432:5432
    volumes:
      - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: vivos-em-nos-pwa
      POSTGRES_PASSWORD: 3x4mpl3

  web:
    image: nossas/vivo-em-nos
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/code
    links:
      - data:data.vivos-em-nos.devel
      - img:img.vivos-em-nos.devel
    environment:
      GRAPHQL_URL: http://data.vivos-em-nos.devel
      WEB_CONCURRENCY: 1
      WEB_MEMORY: 256
      NEW_RELIC_NO_CONFIG_FILE: 1
      NEW_RELIC_ENABLED: 0

  data:
    image: nossas/bonde-graphql
    ports:
      - "3003:3003"
    links:
      - postgres:db.vivo-em-nos.devel
      - img:data.vivo-em-nos.devel
    command: npm run dev
    environment:
      DATABASE_URL: postgres://postgres:3x4mpl3@db.vivo-em-nos.devel:5432/vivos-em-nos-pwa
      PORT: 3003

  img:
    image: h2non/imaginary
    ports:
      - "3009:9000"
    volumes:
      - /tmp/images:/images:Z
    command: "-cors -gzip -enable-url-source -mount /images -http-cache-ttl 0 -allowed-origins http://vivo-em-nos.devel:3000,https://vivosemnos.org,https://vivosennosotros.org"

  # redis:
  #   image: redis:3.2.4-alpine
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - redis-data:/var/lib/redis
  #   command: redis-server --appendonly yes
