export const COUNTRIES = [
  { code: 'BRA', name: 'Brasil' },
  { code: 'MEX', name: 'México' },
  { code: 'ARG', name: 'Argentina' },
  { code: 'VEN', name: 'Venezuela' },
  { code: 'COL', name: 'Colômbia' },
  { code: 'CHL', name: 'Chile' },
  { code: 'PER', name: 'Peru' },
  { code: 'ECU', name: 'Equador' },
  { code: 'DOM', name: 'República Dominicana' },
  { code: 'PRI', name: 'Porto Rico' },
  { code: 'GTM', name: 'Guatemala' },
  { code: 'CRC', name: 'Costa Rica' },
  { code: 'CUB', name: 'Cuba' },
  { code: 'BOL', name: 'Bolívia' },
  { code: 'URY', name: 'Uruguai' },
  { code: 'SLV', name: 'El Salvador' },
  { code: 'PAN', name: 'Panamá' },
  { code: 'PRY', name: 'Paraguai' },
  { code: 'HND', name: 'Honduras' },
  { code: 'TTO', name: 'Trinidad e Tobago' },
  { code: 'NIC', name: 'Nicarágua' },
  { code: 'HTI', name: 'Haiti' },
  { code: 'JAM', name: 'Jamaica' },
  { code: 'BHS', name: 'Bahamas' },
  { code: 'BRB', name: 'Barbados' },
  { code: 'BMU', name: 'Bermudas' },
  { code: 'GUY', name: 'Guiana' },
  { code: 'SUR', name: 'Suriname' },
  { code: 'BLZ', name: 'Belize' },
  { code: 'ABW', name: 'Aruba' },
  { code: 'CYM', name: 'Ilhas Cayman' },
  { code: 'VIR', name: 'Ilhas Virgens Americanas' },
  { code: 'ATG', name: 'Antígua e Barbuda' },
  { code: 'GRD', name: 'Granada' },
  { code: 'VGB', name: 'Ilhas Virgens Britânicas' },
  { code: 'ASM', name: 'Samoa Americana' },
  { code: 'DMA', name: 'Dominica' },
  { code: 'TCA', name: 'Ilhas Turcas e Caicos' },
  { code: 'AIA', name: 'Anguilla' },
  { code: 'FLK', name: 'Ilhas Malvinas' },
  { code: 'MSR', name: 'Montserrat' },
]
